jwt:
  secret: $3cr3t
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 10000
user_service:
  http_url: http://localhost:10001/api
  grpc_url: http://localhost:10011
operation_service:
  url: http://localhost:10002/api
stats_service:
  url: http://localhost:10003/api
