jwt:
  secret: $3cr3t
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 10000
user_service:
  url: http://us-app:10001/api
operation_service:
  url: http://os-app:10002/api
stats_service:
  url: http://ss-app:10003/api
