jwt:
  secret: $3cr3t

http:
  ip: 0.0.0.0
  port: 10000
  cors:
    allowed-methods: [ "GET", "POST", "PATCH", "PUT", "DELETE" ]
    allowed-origins:
      - "http://localhost:3000"
    allow-credentials: true
    allowed-headers:
      - "Authorization"
      - "Location"
      - "Charset"
      - "Access-Control-Allow-Origin"
      - "Content-Type"
      - "Origin"
      - "Accept"
      - "Content-Length"
      - "Accept-Encoding"
      - "X-CSRF-Token"
    exposed-headers:
      - "Location"
      - "Authorization"
      - "Content-Disposition"

user_service:
  http_url: http://localhost:10001/api
  grpc_url: 0.0.0.0:10011
  connect_with_grpc: true
operation_service:
  url: http://localhost:10002/api
stats_service:
  url: http://localhost:10003/api


